version: '3'
services:
  web:
    image: tungxd96/doc-render-service:drs-server
    container_name: drs-server
    build: .
    command: npm run start
    volumes:
      - .:/root/app/
      - /root/app/node_modules
    ports:
      - "8080:8080"