services:
  web:
    image: tungxd96/doc-render-service:drs-server
    container_name: drs-server
    build:
      context: .
    command: npm run start
    volumes:
      - ./:/app
    ports:
      - "8080:8080"